name: "Version aware image pusher"
description: "Will re-tag the docker image to create images for parent versions. For example, if the image is tagged 1.2.3, it will create a tag for 1.2 and 1.0 as well."

inputs:
  package:
    required: true
  platform_name:
    required: true
  version:
    required: true
  gh_token:
    description: "GitHub token to use for authentication."
    required: true
  has_hierarchy:
    description: "Set to true if the image has a hierarchy, this will trigger the tagging of the parent versions."
    required: true
    default: false
  minor_parent:
    description: "Set to true if the image has a minor parent, this will trigger the tagging of the parent versions."
    required: true
  major_parent:
    description: "Set to true if the image has a major parent, this will trigger the tagging of the parent versions."
    required: true
  
runs:
  using: "composite"
  steps:
    - name: Fetch docker image from cache
      uses: actions/cache/restore@v4
      with:
        path: /tmp/${{ github.sha }}-${{ inputs.package }}-${{ inputs.platform_name }}-${{ inputs.version }}.tar
        key: ${{ github.sha }}-${{ inputs.package }}-${{ inputs.platform_name }}-${{ inputs.version }}
        fail-on-cache-miss: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.gh_token }}
    - name: Load image into Docker
      shell: bash
      run: |
        docker load --input /tmp/${{ github.sha }}-${{ inputs.package }}-${{ inputs.platform_name }}-${{ inputs.version }}.tar
    - name: List docker images
      shell: bash
      run: docker images
    - name: Push to registry
      if: ${{ inputs.has_hierarchy != 'true' }}
      shell: bash
      run: |   
    - name: Tag and push parent versions
      shell: bash
      if: ${{ inputs.has_hierarchy == 'true' }}
      run: |
        echo "Tagging parent versions with ${{ inputs.version }}, ${{ inputs.minor_parent }} and ${{ inputs.major_parent }}"
        docker tag ghcr.io/${{ github.repository_owner }}/rafiki-${{ inputs.package }}-${{ inputs.platform_name }}:${{ inputs.version }} ghcr.io/${{ github.repository_owner }}/rafiki-${{ inputs.package }}-${{ inputs.platform_name }}:${{ inputs.major_parent }}
        docker tag ghcr.io/${{ github.repository_owner }}/rafiki-${{ inputs.package }}-${{ inputs.platform_name }}:${{ inputs.version }} ghcr.io/${{ github.repository_owner }}/rafiki-${{ inputs.package }}-${{ inputs.platform_name }}:${{ inputs.minor_parent }}
        echo "Pushing tagged images to registry"
        docker push ghcr.io/${{ github.repository_owner }}/rafiki-${{ inputs.package }}-${{ inputs.platform_name }}:${{ inputs.version }}        
        docker push ghcr.io/${{ github.repository_owner }}/rafiki-${{ inputs.package }}-${{ inputs.platform_name }}:${{ inputs.major_parent }}
        docker push ghcr.io/${{ github.repository_owner }}/rafiki-${{ inputs.package }}-${{ inputs.platform_name }}:${{ inputs.minor_parent }}
